# Loads default set of integrations. Do not remove.
default_config: {}

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml  # Optional: ensures YAML mode; skip if already set
  dashboards:
    solar-assistant:
      mode: yaml
      title: Solar Assistant
      icon: mdi:solar-power
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/solar-assistant.yaml
  resources:
    - url: /local/community/energy-gauge-bundle-card/energy-gauge-bundle-card.js
      type: module
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/community/lovelace-card-mod/card-mod.js
      type: module
    - url: /local/community/button-card/button-card.js
      type: module
    - url: /local/community/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /local/community/apexcharts-card/apexcharts-card.js
      type: module
    - url: /local/community/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /local/community/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /local/community/weather-radar-card/weather-radar-card.js
      type: module
    - url: /local/community/light-entity-card/light-entity-card.js
      type: module
    - url: /local/community/my-cards/my-cards.js
      type: module
    - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /local/community/battery-state-card/battery-state-card.js
      type: module

udp:
  port: 50222
  local_ip: 192.168.1.100  # Your HA instance IP
  
sensor:
  - platform: template
    sensors:
      windy_lat:
        friendly_name: "Fixed Weather Latitude"
        value: "38.3368"  # From 38°20'12.5"N
        icon: mdi:latitude
      windy_lon:
        friendly_name: "Fixed Weather Longitude" 
        value: "-114.1268"  # From 114°07'36.4"W
        icon: mdi:longitude

panel_iframe:
  windy:
    title: "Windy"
    icon: mdi:weather-windy
    url: "https://www.windy.com"

