# Loads default set of integrations. Do not remove.
default_config: {}

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml  # Optional: ensures YAML mode; skip if already set
  dashboards:
    solar-assistant:
      mode: yaml
      title: Solar Assistant
      icon: mdi:solar-power
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/solar-assistant.yaml
    weather-center:
      mode: yaml
      title: Weather Center
      icon: mdi:weather-cloudy
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/weather-center.yaml
  resources:
    - url: /local/community/energy-gauge-bundle-card/energy-gauge-bundle-card.js
      type: module
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/community/lovelace-card-mod/card-mod.js
      type: module
    - url: /local/community/button-card/button-card.js
      type: module
    - url: /local/community/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /local/community/apexcharts-card/apexcharts-card.js
      type: module
    - url: /local/community/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /local/community/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /local/community/weather-radar-card/weather-radar-card.js
      type: module
    - url: /local/community/light-entity-card/light-entity-card.js
      type: module
    - url: /local/community/my-cards/my-cards.js
      type: module
    - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /local/community/battery-state-card/battery-state-card.js
      type: module
    - url: /local/community/compass-card/compass-card.js
      type: module
    - url: /local/community/lovelace-paper-buttons-row/paper-buttons-row.js
      type: module
    - url: /local/community/config-template-card/config-template-card.js
      type: module
    - url: /local/community/lovelace-windrose-card/windrose-card.js
      type: module

panel_iframe:
  windy:
    title: "Windy"
    icon: mdi:weather-windy
    url: "https://www.windy.com/"

template:
  - sensor:
      - name: "Windy Latitude"
        state: 38.3368
        unit_of_measurement: "°"
        icon: mdi:latitude
      - name: "Windy Longitude"
        state: -114.1268  # Negative for West
        unit_of_measurement: "°" 
        icon: mdi:longitude


sensor:
  - platform: statistics
    name: "Barometric Pressure 24h Spread"
    entity_id: sensor.st_00174194_air_pressure
    state_characteristic: distance_absolute
    max_age:
      hours: 24
    unit_of_measurement: "inHg"

weatherflow:
  api_token: 83b04b0d-dc6a-402f-91b7-28748e8e0f66
  station_id: 170071


template:
  - sensor:
      - name: "Pressure Trend Icon"
        state: >-
          {% set trend = states('sensor.weatherflow_pressure_trend') %}
          {{ 'rising' if trend|float > 0.1 else 'falling' if trend|float < -0.1 else 'steady' }}


